-- Seed: the 40 MCU feature films.
--
-- Descriptions are the originals from the design. They are marked 'authored'
-- so the weekly sync never overwrites them, and they serve as the few-shot
-- style reference when a description is generated for a newly added film.
--
-- Generated by scripts/generate-seed.mjs — edit that, not this.

INSERT INTO films (id, title, release_date, phase, saga, description, description_source, media_type, updated_at) VALUES
	('ironman', 'Iron Man', '2008-05-02', 1, 'The Infinity Saga', 'Tony Stark builds the first suit in a cave, then tells the world who he is.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('hulk', 'The Incredible Hulk', '2008-06-13', 1, 'The Infinity Saga', 'Banner hides out in Brazil while the army hunts him; ends in a Harlem street brawl.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('ironman2', 'Iron Man 2', '2010-05-07', 1, 'The Infinity Saga', 'Whiplash and his electric whips, Justin Hammer, and Black Widow''s first appearance.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('thor', 'Thor', '2011-05-06', 1, 'The Infinity Saga', 'A banished Asgardian prince learns humility in a small New Mexico desert town.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('cap1', 'Captain America: The First Avenger', '2011-07-22', 1, 'The Infinity Saga', 'WWII origin story: skinny Steve, the Red Skull, and a plane going into the ice.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('avengers', 'The Avengers', '2012-05-04', 1, 'The Infinity Saga', 'Loki opens a portal over New York and the team assembles for the first time.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('ironman3', 'Iron Man 3', '2013-05-03', 2, 'The Infinity Saga', 'Post-New York panic attacks, the Mandarin twist, and the Malibu house in the sea.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('darkworld', 'Thor: The Dark World', '2013-11-08', 2, 'The Infinity Saga', 'Malekith wants the Aether; the finale is a portal fight through Greenwich.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('wintersoldier', 'Captain America: The Winter Soldier', '2014-04-04', 2, 'The Infinity Saga', 'S.H.I.E.L.D. turns out to be Hydra, and Bucky comes back as a masked assassin.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('gotg', 'Guardians of the Galaxy', '2014-08-01', 2, 'The Infinity Saga', 'Star-Lord''s mixtape, a talking raccoon and a tree, and Ronan on Xandar.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('ultron', 'Avengers: Age of Ultron', '2015-05-01', 2, 'The Infinity Saga', 'Tony''s peacekeeping AI goes rogue and lifts the city of Sokovia into the sky.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('antman', 'Ant-Man', '2015-07-17', 2, 'The Infinity Saga', 'Scott Lang steals a shrinking suit; the climax happens on a Thomas the Tank Engine set.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('civilwar', 'Captain America: Civil War', '2016-05-06', 3, 'The Infinity Saga', 'The Accords split the team in two, leading to the airport fight in Leipzig.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('strange', 'Doctor Strange', '2016-11-04', 3, 'The Infinity Saga', 'An arrogant surgeon becomes a sorcerer and bargains Dormammu into submission.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('gotg2', 'Guardians of the Galaxy Vol. 2', '2017-05-05', 3, 'The Infinity Saga', 'Peter meets his father Ego, a living planet, and Yondu gets a Ravager funeral.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('homecoming', 'Spider-Man: Homecoming', '2017-07-07', 3, 'The Infinity Saga', 'High-school Peter takes on the Vulture, who turns out to be his date''s dad.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('ragnarok', 'Thor: Ragnarok', '2017-11-03', 3, 'The Infinity Saga', 'Hela destroys Asgard while Thor is stuck as a gladiator on Sakaar fighting Hulk.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('blackpanther', 'Black Panther', '2018-02-16', 3, 'The Infinity Saga', 'T''Challa takes the Wakandan throne and Killmonger challenges him for it.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('infinitywar', 'Avengers: Infinity War', '2018-04-27', 3, 'The Infinity Saga', 'Thanos collects all six stones and snaps half of everyone out of existence.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('antman2', 'Ant-Man and the Wasp', '2018-07-06', 3, 'The Infinity Saga', 'A rescue mission into the Quantum Realm for Janet; ends right on the snap.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('captainmarvel', 'Captain Marvel', '2019-03-08', 3, 'The Infinity Saga', 'A 90s prequel with Carol Danvers, shape-shifting Skrulls and a two-eyed Fury.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('endgame', 'Avengers: Endgame', '2019-04-26', 3, 'The Infinity Saga', 'Five years later, the time heist, and Tony''s sacrifice to undo the snap.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('farfromhome', 'Spider-Man: Far From Home', '2019-07-02', 3, 'The Infinity Saga', 'School trip through Europe where Mysterio fakes monsters with drone illusions.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('blackwidow', 'Black Widow', '2021-07-09', 4, 'The Multiverse Saga', 'Natasha reunites with her fake Russian family and shuts down the Red Room.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('shangchi', 'Shang-Chi and the Legend of the Ten Rings', '2021-09-03', 4, 'The Multiverse Saga', 'The bus fight in San Francisco, then the hidden village of Ta Lo and a dragon.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('eternals', 'Eternals', '2021-11-05', 4, 'The Multiverse Saga', 'Immortals who have been on Earth for millennia stop a Celestial hatching out of it.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('nowayhome', 'Spider-Man: No Way Home', '2021-12-17', 4, 'The Multiverse Saga', 'A memory spell goes wrong and pulls in villains and Spider-Men from other universes.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('multiverse', 'Doctor Strange in the Multiverse of Madness', '2022-05-06', 4, 'The Multiverse Saga', 'Wanda hunts America Chavez across realities; the Illuminati do not last long.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('loveandthunder', 'Thor: Love and Thunder', '2022-07-08', 4, 'The Multiverse Saga', 'Gorr the God Butcher, screaming goats, and Jane Foster wielding Mjolnir.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('wakandaforever', 'Black Panther: Wakanda Forever', '2022-11-11', 4, 'The Multiverse Saga', 'Wakanda grieves T''Challa while Namor rises from the underwater city of Talokan.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('quantumania', 'Ant-Man and the Wasp: Quantumania', '2023-02-17', 5, 'The Multiverse Saga', 'The whole Lang family gets stuck in the Quantum Realm with Kang the Conqueror.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('gotg3', 'Guardians of the Galaxy Vol. 3', '2023-05-05', 5, 'The Multiverse Saga', 'Rocket''s brutal backstory, the High Evolutionary, and the crew going separate ways.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('marvels', 'The Marvels', '2023-11-10', 5, 'The Multiverse Saga', 'Carol, Kamala and Monica keep swapping places whenever they use their powers.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('deadpool', 'Deadpool & Wolverine', '2024-07-26', 5, 'The Multiverse Saga', 'Wade drags a broken Wolverine variant through the TVA and into the Void.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('bravenewworld', 'Captain America: Brave New World', '2025-02-14', 5, 'The Multiverse Saga', 'Sam Wilson as Cap, and President Ross turning into the Red Hulk.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('thunderbolts', 'Thunderbolts*', '2025-05-02', 5, 'The Multiverse Saga', 'A squad of leftover antiheroes led by Yelena, up against Sentry and the Void.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('ff', 'The Fantastic Four: First Steps', '2025-07-25', 6, 'The Multiverse Saga', 'A retro-futuristic 1960s Earth defending itself from Galactus and the Silver Surfer.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('brandnewday', 'Spider-Man: Brand New Day', '2026-07-31', 6, 'The Multiverse Saga', 'Peter fights crime full-time in a world that no longer remembers who he is.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('doomsday', 'Avengers: Doomsday', '2026-12-18', 6, 'The Multiverse Saga', 'Heroes from three universes collide with Doctor Doom.', 'authored', 'movie', '2026-08-02T00:00:00.000Z'),
	('secretwars', 'Avengers: Secret Wars', '2027-12-17', 6, 'The Multiverse Saga', 'The finale of the Multiverse Saga.', 'authored', 'movie', '2026-08-02T00:00:00.000Z');
